apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  keycloakhost: idm-dev.slix-cloud.de
  keycloakhostmonitoring: idm-dev.slix-cloud.de
  keycloakdbhost: lpdev.workersub.clusternet.oraclevcn.com
  tektonhost: tekton.local.com
  grafanahost: monitoring.slix-cloud.de
  jenkinshost: jenkins.slix-cloud.de
  clustername: observabilitycluster
  environment: DEV
  smtppasskey: ad287eae-400f-4d3d-b4ce-b3d361e8ca79
  clientmanagement_ociconfigkey: 120e053a-cdb7-4e28-8b24-9e90b6ccd4bc
  #externalsecrets_version: "0.16.0"
  s3ocicompartement: "ocid1.compartment.oc1..aaaaaaaa2e35vmqjoxpe3vrtrgozb6ubvis2ecifjtxer2acyo5iwlqp3sxq"
  s3region: eu-frankfurt-1
  s3endpoint: "https://frsjez6mlvwx.compat.objectstorage.eu-frankfurt-1.oraclecloud.com"
  s3userkey: b824ee5b-b9d8-4ee0-a8b9-62821caa3879
  imagepolicy: $imagepolicy
  externalip: "193.122.55.41"
  externalip_gateway: "192.168.64.7"
  fluxuiurl: "flux.local.com"
  provisioningbuckets: "loki,tempo,pyroscope"