apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./03_grafana
  prune: true
  dependsOn:
    - name: prometheus
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
  sourceRef:
    kind: GitRepository
    name: flux-system-observability
  