resources:
- cluster-config.yaml
- flux-app.yaml
- envoy-gateway.yaml
- repoResourceSet.yaml
- s3-backend.yaml
- prometheus.yaml
- alloy.yaml
- cert-manager.yaml
- grafana.yaml
- loki.yaml
- tempo.yaml
- beyla.yaml
- pyroscope.yaml
- rideshare-demo.yaml
