apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: fluxrepos
  namespace: flux-system
spec:
  inputs:
  - name: envoy
    oci: true
    url: oci://docker.io/envoyproxy
  - name: rustfs
    oci: false
    url: https://charts.rustfs.com
  - name: prometheus
    oci: false
    url: https://prometheus-community.github.io/helm-charts
  - name: onlineboutique
    oci: true
    url: oci://us-docker.pkg.dev/online-boutique-ci/charts
  - name: grafana
    oci: false
    url: https://grafana.github.io/helm-charts
  - name: grafana-community
    oci: false
    url: https://grafana-community.github.io/helm-charts
  - name: cert-manager
    oci: false
    url: https://charts.jetstack.io
  resourcesTemplate: |
    ---
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: HelmRepository
    metadata:
      name: << inputs.name >>
      namespace: << inputs.provider.namespace >>
    spec:
      <<- if inputs.oci >>
      type: oci
      <<- end >>
      interval: 60m0s
      url: << inputs.url >>
    