apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rideshare
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./13_rideshare
  prune: true
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
  sourceRef:
    kind: GitRepository
    name: flux-system-observability