apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.7.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  components:
    - source-controller
    - source-watcher
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: kubernetes
    size: small
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  storage:
    #class: "oci-bv"
    size: "25Gi"
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux
  sync:
    name: flux-system-observability
    kind: GitRepository
    url: https://github.com/slix-gmbh/workshop-master.git
    ref: "refs/heads/main"
    path: ./00_common/observabilityworkshop
    pullSecret: "github-token"