apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: fluxRepos
  namespace: flux-system
spec:
  inputs:
  - name: "mandanten"
    url: https://bitbucket.org/slixrepo/slimx-mandanten.git
    branch: master
  resources:
  - apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: << inputs.name >>
      namespace: << inputs.provider.namespace >>
    spec:
      interval: 1m0s
      ref:
        branch: << inputs.branch >>
      secretRef:
        name: flux-system
      url: << inputs.url >>