apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustfs
  namespace: rustfs
spec:
  interval: 5m
  chart:
    spec:
      chart: rustfs
      sourceRef:
        kind: HelmRepository
        name: rustfs
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: values-rustfs