management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=rideshare-auto
management.metrics.web.server.request.autotime.enabled=true
