apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beyla
  namespace: beyla
spec:
  interval: 5m
  chart:
    spec:
      chart: beyla
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: values-beyla