apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-plugins
  labels:
    grafana_plugin: "1"
data:
  plugin.yaml: |-
    apiVersion: 1
    apps:
      - type: grafana-pyroscope-app
        jsonData:
          backendUrl: http://pyroscope.pyroscope.svc.cluster.local:4040
        secureJsonData: