apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-credentials
  namespace: loki
stringData:
  S3_ACCESS_KEY_ID: rustfsadmin
  S3_SECRET_ACCESS_KEY: rustfsadmin
  ENDPOINT: http://rustfs-svc.rustfs.svc.cluster.local:9000
  