resources:
- namespace.yaml

namespace: pyroscope

commonLabels:
    app.kubernetes.io/part-of: pyroscope
    app.kubernetes.io/component: monitoring

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: values-pyroscope
    namespace: pyroscope
    files:
    - values.yaml=values-pyroscope.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
  - name: pyroscope-dashboards
    files:
      - dashboards/pyroscope-reads.json
      - dashboards/pyroscope-writes.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: pyroscope
        app.kubernetes.io/component: monitoring