apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: flux-system
stringData:
  username: thorsten@slix.de
  password: <token>

# Worst Practise... Sollte mit ExternalSecrets oder SealedSecrets oder SOPS verschlüsselt sein